development:
  adapter: mysql2
  encoding: utf8
  host: localhost
  database: fest_schedule_development
  username: root
  password: 

test:
  adapter: sqlite3
  database: ":memory:"
  verbosity: silent
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  encoding: utf8
  host: localhost
  database: fest_schedule_2011_production
  username: rails
  password: rails